const PlayerDeck = [
    {
        "id": 01,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 02,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 03,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 04,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 05,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
];


const OpponentDeck = [
    {
        "id": 06,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 07,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 08,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 09,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
    {
        "id": 10,
        "name": 'Raven',
        "owner": 'player',
        "image": '/images/.png',
        "up": 5,
        "right": 6,
        "down": 2,
        "left": 7,
    },
];

export { PlayerDeck, OpponentDeck };
